"""empty message

Revision ID: 0d217d8b671c
Revises: 3c70f19de736
Create Date: 2019-04-07 15:04:42.083084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d217d8b671c'
down_revision = '3c70f19de736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('siteuser', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('siteuser', 'age')
    # ### end Alembic commands ###
