"""users table

Revision ID: 2139fb156c64
Revises: 2960067558f6
Create Date: 2018-12-22 21:53:59.767953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2139fb156c64'
down_revision = '2960067558f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'list',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('siteuser', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'siteuser', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'siteuser', type_='unique')
    op.alter_column('siteuser', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profile', 'list',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
