"""users table

Revision ID: 2960067558f6
Revises: 6d7cc0df2f49
Create Date: 2018-12-22 21:17:00.816366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2960067558f6'
down_revision = '6d7cc0df2f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('siteuser_username_key', 'siteuser', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('siteuser_username_key', 'siteuser', ['username'])
    # ### end Alembic commands ###
