"""users table

Revision ID: 6d7cc0df2f49
Revises: c956075e00cd
Create Date: 2018-12-22 21:12:33.115116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7cc0df2f49'
down_revision = 'c956075e00cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'list',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('siteuser', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('siteuser', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profile', 'list',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
