"""empty message

Revision ID: bd8733b88510
Revises: b4d2265a0a8f
Create Date: 2019-04-03 14:47:56.868605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8733b88510'
down_revision = 'b4d2265a0a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('siteuser', sa.Column('privilege', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('siteuser', 'privilege')
    # ### end Alembic commands ###
