"""empty message

Revision ID: bddd47b1d9f2
Revises: 1b7aa3ffea77
Create Date: 2019-04-03 12:44:59.149036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bddd47b1d9f2'
down_revision = '1b7aa3ffea77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('siteuser', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('siteuser', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('siteuser', 'country')
    op.drop_column('siteuser', 'age')
    # ### end Alembic commands ###
